version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always


  chat:
    image: gabrielbuehler/transferarbeit
    restart: always
    ports:
      - 9900:3000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  
    